// ******************************************************************************************************
// Copyright 2022 Mapped Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ******************************************************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: mapped/cloud/api/control/control.proto

package control

import (
	types "go.mapped.dev/pb/cloud/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WritePropRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The property value(s) to write
	Payload *PointReferenceAndValue `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// The timeout for each request to each subtended device in milliseconds
	// NOTE: UGAgent makes every attempt to parallelize these, but some devices don't support
	//
	//	writing multiple properties at once, which means write requests must be serialized
	TimeoutInMs uint32 `protobuf:"varint,2,opt,name=timeout_in_ms,json=timeoutInMs,proto3" json:"timeout_in_ms,omitempty"`
	// A list of [delay, mappingKeys] to poll after a successful write
	PostWritePollRequests []*PostWritePollRequest `protobuf:"bytes,3,rep,name=post_write_poll_requests,json=postWritePollRequests,proto3" json:"post_write_poll_requests,omitempty"`
	// Simulate the command by only validating the input and logging
	// do not send an actual command over the wire
	Simulate bool `protobuf:"varint,100,opt,name=simulate,proto3" json:"simulate,omitempty"`
}

func (x *WritePropRequest) Reset() {
	*x = WritePropRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_api_control_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WritePropRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WritePropRequest) ProtoMessage() {}

func (x *WritePropRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_api_control_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WritePropRequest.ProtoReflect.Descriptor instead.
func (*WritePropRequest) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_api_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *WritePropRequest) GetPayload() *PointReferenceAndValue {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WritePropRequest) GetTimeoutInMs() uint32 {
	if x != nil {
		return x.TimeoutInMs
	}
	return 0
}

func (x *WritePropRequest) GetPostWritePollRequests() []*PostWritePollRequest {
	if x != nil {
		return x.PostWritePollRequests
	}
	return nil
}

func (x *WritePropRequest) GetSimulate() bool {
	if x != nil {
		return x.Simulate
	}
	return false
}

type WritePropResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique ID of this request to be provided to Mapped Support
	// for troubleshooting in the case of unexpected errors
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The result of each property write
	Payload *PointReferenceAndResult `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *WritePropResponse) Reset() {
	*x = WritePropResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_api_control_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WritePropResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WritePropResponse) ProtoMessage() {}

func (x *WritePropResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_api_control_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WritePropResponse.ProtoReflect.Descriptor instead.
func (*WritePropResponse) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_api_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *WritePropResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WritePropResponse) GetPayload() *PointReferenceAndResult {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PointReferenceAndValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The `point.id` or `point.mappingKey` where the value originated from or is to be written to
	PointReferenceId string `protobuf:"bytes,1,opt,name=point_reference_id,json=pointReferenceId,proto3" json:"point_reference_id,omitempty"`
	// The value read or to be written
	// NOTE: The value *type* must NOT change type between a read and a write
	Value *types.TypedValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// [optional]
	// If writing to a single array index, this is the ZERO-BASED index to write to
	//   - For BACnet, this can be either a priority or an array index - but note that it is zero-based
	//     vs BACnet which is one-based (zero in BACnet is the array length), so passing 0 here will write
	//     to BACnet priority 1, and passing 1 here will write to BACnet priority 2, etc...
	Index *wrapperspb.UInt32Value `protobuf:"bytes,10,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *PointReferenceAndValue) Reset() {
	*x = PointReferenceAndValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_api_control_control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointReferenceAndValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointReferenceAndValue) ProtoMessage() {}

func (x *PointReferenceAndValue) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_api_control_control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointReferenceAndValue.ProtoReflect.Descriptor instead.
func (*PointReferenceAndValue) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_api_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *PointReferenceAndValue) GetPointReferenceId() string {
	if x != nil {
		return x.PointReferenceId
	}
	return ""
}

func (x *PointReferenceAndValue) GetValue() *types.TypedValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PointReferenceAndValue) GetIndex() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Index
	}
	return nil
}

type PointReferenceAndResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The `point.id` or `point.mappingKey` provided to the write request
	PointReferenceId string `protobuf:"bytes,1,opt,name=point_reference_id,json=pointReferenceId,proto3" json:"point_reference_id,omitempty"`
	// The result code
	Result types.ControlResult `protobuf:"varint,2,opt,name=result,proto3,enum=mapped.cloud.types.ControlResult" json:"result,omitempty"`
	// Error description (if available)
	ErrorDescription string `protobuf:"bytes,3,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	// Protocol-specific error class, for protocols that split class/code - like BACnet
	ConnectorErrorClass int64 `protobuf:"varint,4,opt,name=connector_error_class,json=connectorErrorClass,proto3" json:"connector_error_class,omitempty"`
	// Protocol-specific error code
	ConnectorErrorCode int64 `protobuf:"varint,5,opt,name=connector_error_code,json=connectorErrorCode,proto3" json:"connector_error_code,omitempty"`
}

func (x *PointReferenceAndResult) Reset() {
	*x = PointReferenceAndResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_api_control_control_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointReferenceAndResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointReferenceAndResult) ProtoMessage() {}

func (x *PointReferenceAndResult) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_api_control_control_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointReferenceAndResult.ProtoReflect.Descriptor instead.
func (*PointReferenceAndResult) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_api_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *PointReferenceAndResult) GetPointReferenceId() string {
	if x != nil {
		return x.PointReferenceId
	}
	return ""
}

func (x *PointReferenceAndResult) GetResult() types.ControlResult {
	if x != nil {
		return x.Result
	}
	return types.ControlResult(0)
}

func (x *PointReferenceAndResult) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

func (x *PointReferenceAndResult) GetConnectorErrorClass() int64 {
	if x != nil {
		return x.ConnectorErrorClass
	}
	return 0
}

func (x *PointReferenceAndResult) GetConnectorErrorCode() int64 {
	if x != nil {
		return x.ConnectorErrorCode
	}
	return 0
}

type PostWritePollRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// How long to wait after a write operation before polling the list of point references
	// for updated values? Must be greater than `0`.
	DelaySeconds uint32 `protobuf:"varint,1,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	// The list of point references (id or mappingKey) that should be polled after delay_seconds
	// ... for point reference entries in the list that do not include a specific property, the
	//
	//	default set of "polling" properties for the associated protocols is polled. In
	//	the case of bacnet that is `polling_properties` (or `[85]` if that is not set)
	PointReferenceIds []string `protobuf:"bytes,2,rep,name=point_reference_ids,json=pointReferenceIds,proto3" json:"point_reference_ids,omitempty"`
}

func (x *PostWritePollRequest) Reset() {
	*x = PostWritePollRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_api_control_control_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostWritePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostWritePollRequest) ProtoMessage() {}

func (x *PostWritePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_api_control_control_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostWritePollRequest.ProtoReflect.Descriptor instead.
func (*PostWritePollRequest) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_api_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *PostWritePollRequest) GetDelaySeconds() uint32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *PostWritePollRequest) GetPointReferenceIds() []string {
	if x != nil {
		return x.PointReferenceIds
	}
	return nil
}

var File_mapped_cloud_api_control_control_proto protoreflect.FileDescriptor

var file_mapped_cloud_api_control_control_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x1a, 0x24, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64,
	0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70,
	0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x02, 0x0a, 0x10, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x4a, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x30, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x69, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x49, 0x6e, 0x4d, 0x73, 0x12,
	0x67, 0x0a, 0x18, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x70, 0x6f,
	0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2e, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x15, 0x70, 0x6f, 0x73, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x69, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x22, 0x7f, 0x0a, 0x11, 0x57, 0x72, 0x69, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x4b, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6d, 0x61, 0x70, 0x70,
	0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xb0, 0x01, 0x0a, 0x16, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x2c, 0x0a, 0x12, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x34,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x95, 0x02, 0x0a, 0x17, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x39, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a,
	0x11, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x15, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x30,
	0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x22, 0x6b, 0x0a, 0x14, 0x50, 0x6f, 0x73, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x50, 0x6f, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x61,
	0x79, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0c, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x2e, 0x0a,
	0x13, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x73, 0x42, 0x67, 0x0a,
	0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x01, 0x5a,
	0x2a, 0x67, 0x6f, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x70,
	0x62, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x3b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0xaa, 0x02, 0x18, 0x4d, 0x61,
	0x70, 0x70, 0x65, 0x64, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mapped_cloud_api_control_control_proto_rawDescOnce sync.Once
	file_mapped_cloud_api_control_control_proto_rawDescData = file_mapped_cloud_api_control_control_proto_rawDesc
)

func file_mapped_cloud_api_control_control_proto_rawDescGZIP() []byte {
	file_mapped_cloud_api_control_control_proto_rawDescOnce.Do(func() {
		file_mapped_cloud_api_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapped_cloud_api_control_control_proto_rawDescData)
	})
	return file_mapped_cloud_api_control_control_proto_rawDescData
}

var file_mapped_cloud_api_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mapped_cloud_api_control_control_proto_goTypes = []interface{}{
	(*WritePropRequest)(nil),        // 0: mapped.cloud.api.control.WritePropRequest
	(*WritePropResponse)(nil),       // 1: mapped.cloud.api.control.WritePropResponse
	(*PointReferenceAndValue)(nil),  // 2: mapped.cloud.api.control.PointReferenceAndValue
	(*PointReferenceAndResult)(nil), // 3: mapped.cloud.api.control.PointReferenceAndResult
	(*PostWritePollRequest)(nil),    // 4: mapped.cloud.api.control.PostWritePollRequest
	(*types.TypedValue)(nil),        // 5: mapped.cloud.types.TypedValue
	(*wrapperspb.UInt32Value)(nil),  // 6: google.protobuf.UInt32Value
	(types.ControlResult)(0),        // 7: mapped.cloud.types.ControlResult
}
var file_mapped_cloud_api_control_control_proto_depIdxs = []int32{
	2, // 0: mapped.cloud.api.control.WritePropRequest.payload:type_name -> mapped.cloud.api.control.PointReferenceAndValue
	4, // 1: mapped.cloud.api.control.WritePropRequest.post_write_poll_requests:type_name -> mapped.cloud.api.control.PostWritePollRequest
	3, // 2: mapped.cloud.api.control.WritePropResponse.payload:type_name -> mapped.cloud.api.control.PointReferenceAndResult
	5, // 3: mapped.cloud.api.control.PointReferenceAndValue.value:type_name -> mapped.cloud.types.TypedValue
	6, // 4: mapped.cloud.api.control.PointReferenceAndValue.index:type_name -> google.protobuf.UInt32Value
	7, // 5: mapped.cloud.api.control.PointReferenceAndResult.result:type_name -> mapped.cloud.types.ControlResult
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_mapped_cloud_api_control_control_proto_init() }
func file_mapped_cloud_api_control_control_proto_init() {
	if File_mapped_cloud_api_control_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mapped_cloud_api_control_control_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WritePropRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_api_control_control_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WritePropResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_api_control_control_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointReferenceAndValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_api_control_control_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointReferenceAndResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_api_control_control_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostWritePollRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapped_cloud_api_control_control_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapped_cloud_api_control_control_proto_goTypes,
		DependencyIndexes: file_mapped_cloud_api_control_control_proto_depIdxs,
		MessageInfos:      file_mapped_cloud_api_control_control_proto_msgTypes,
	}.Build()
	File_mapped_cloud_api_control_control_proto = out.File
	file_mapped_cloud_api_control_control_proto_rawDesc = nil
	file_mapped_cloud_api_control_control_proto_goTypes = nil
	file_mapped_cloud_api_control_control_proto_depIdxs = nil
}
