// ******************************************************************************************************
// Copyright 2022 Mapped Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ******************************************************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: mapped/cloud/types/bacnet.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BacnetObjectType int32

const (
	// NOTE: Actual BACnet start starts enum from 0, but to follow protobuf's convention, we shift all by 1 to preserve 0 for UNSPECIFIED. E.g., analogInput in BACnet spec is actually 0, but we use 1.
	BacnetObjectType_BACNET_OBJECT_TYPE_UNSPECIFIED BacnetObjectType = 0
	BacnetObjectType_ANALOG_INPUT                   BacnetObjectType = 1
	BacnetObjectType_ANALOG_OUTPUT                  BacnetObjectType = 2
	BacnetObjectType_ANALOG_VALUE                   BacnetObjectType = 3
	BacnetObjectType_BINARY_INPUT                   BacnetObjectType = 4
	BacnetObjectType_BINARY_OUTPUT                  BacnetObjectType = 5
	BacnetObjectType_BINARY_VALUE                   BacnetObjectType = 6
	BacnetObjectType_DEVICE                         BacnetObjectType = 9
	BacnetObjectType_MULTISTATE_INPUT               BacnetObjectType = 14
	BacnetObjectType_MULTISTATE_OUTPUT              BacnetObjectType = 15
	BacnetObjectType_MULTISTATE_VALUE               BacnetObjectType = 16
)

// Enum value maps for BacnetObjectType.
var (
	BacnetObjectType_name = map[int32]string{
		0:  "BACNET_OBJECT_TYPE_UNSPECIFIED",
		1:  "ANALOG_INPUT",
		2:  "ANALOG_OUTPUT",
		3:  "ANALOG_VALUE",
		4:  "BINARY_INPUT",
		5:  "BINARY_OUTPUT",
		6:  "BINARY_VALUE",
		9:  "DEVICE",
		14: "MULTISTATE_INPUT",
		15: "MULTISTATE_OUTPUT",
		16: "MULTISTATE_VALUE",
	}
	BacnetObjectType_value = map[string]int32{
		"BACNET_OBJECT_TYPE_UNSPECIFIED": 0,
		"ANALOG_INPUT":                   1,
		"ANALOG_OUTPUT":                  2,
		"ANALOG_VALUE":                   3,
		"BINARY_INPUT":                   4,
		"BINARY_OUTPUT":                  5,
		"BINARY_VALUE":                   6,
		"DEVICE":                         9,
		"MULTISTATE_INPUT":               14,
		"MULTISTATE_OUTPUT":              15,
		"MULTISTATE_VALUE":               16,
	}
)

func (x BacnetObjectType) Enum() *BacnetObjectType {
	p := new(BacnetObjectType)
	*p = x
	return p
}

func (x BacnetObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BacnetObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_mapped_cloud_types_bacnet_proto_enumTypes[0].Descriptor()
}

func (BacnetObjectType) Type() protoreflect.EnumType {
	return &file_mapped_cloud_types_bacnet_proto_enumTypes[0]
}

func (x BacnetObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BacnetObjectType.Descriptor instead.
func (BacnetObjectType) EnumDescriptor() ([]byte, []int) {
	return file_mapped_cloud_types_bacnet_proto_rawDescGZIP(), []int{0}
}

var File_mapped_cloud_types_bacnet_proto protoreflect.FileDescriptor

var file_mapped_cloud_types_bacnet_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x62, 0x61, 0x63, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2a, 0xf3, 0x01, 0x0a, 0x10, 0x42, 0x61, 0x63, 0x6e, 0x65, 0x74,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x1e, 0x42, 0x41,
	0x43, 0x4e, 0x45, 0x54, 0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x41, 0x4e, 0x41, 0x4c, 0x4f, 0x47, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x10, 0x01,
	0x12, 0x11, 0x0a, 0x0d, 0x41, 0x4e, 0x41, 0x4c, 0x4f, 0x47, 0x5f, 0x4f, 0x55, 0x54, 0x50, 0x55,
	0x54, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x4e, 0x41, 0x4c, 0x4f, 0x47, 0x5f, 0x56, 0x41,
	0x4c, 0x55, 0x45, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f,
	0x49, 0x4e, 0x50, 0x55, 0x54, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x49, 0x4e, 0x41, 0x52,
	0x59, 0x5f, 0x4f, 0x55, 0x54, 0x50, 0x55, 0x54, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x49,
	0x4e, 0x41, 0x52, 0x59, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x10, 0x09, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x55, 0x4c, 0x54,
	0x49, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x10, 0x0e, 0x12, 0x15,
	0x0a, 0x11, 0x4d, 0x55, 0x4c, 0x54, 0x49, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x55, 0x54,
	0x50, 0x55, 0x54, 0x10, 0x0f, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x55, 0x4c, 0x54, 0x49, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x10, 0x42, 0x53, 0x0a, 0x16, 0x63,
	0x6f, 0x6d, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x22, 0x67, 0x6f, 0x2e, 0x6d, 0x61, 0x70, 0x70,
	0x65, 0x64, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x73, 0xaa, 0x02, 0x12, 0x4d, 0x61,
	0x70, 0x70, 0x65, 0x64, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mapped_cloud_types_bacnet_proto_rawDescOnce sync.Once
	file_mapped_cloud_types_bacnet_proto_rawDescData = file_mapped_cloud_types_bacnet_proto_rawDesc
)

func file_mapped_cloud_types_bacnet_proto_rawDescGZIP() []byte {
	file_mapped_cloud_types_bacnet_proto_rawDescOnce.Do(func() {
		file_mapped_cloud_types_bacnet_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapped_cloud_types_bacnet_proto_rawDescData)
	})
	return file_mapped_cloud_types_bacnet_proto_rawDescData
}

var file_mapped_cloud_types_bacnet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mapped_cloud_types_bacnet_proto_goTypes = []interface{}{
	(BacnetObjectType)(0), // 0: mapped.cloud.types.BacnetObjectType
}
var file_mapped_cloud_types_bacnet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mapped_cloud_types_bacnet_proto_init() }
func file_mapped_cloud_types_bacnet_proto_init() {
	if File_mapped_cloud_types_bacnet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapped_cloud_types_bacnet_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapped_cloud_types_bacnet_proto_goTypes,
		DependencyIndexes: file_mapped_cloud_types_bacnet_proto_depIdxs,
		EnumInfos:         file_mapped_cloud_types_bacnet_proto_enumTypes,
	}.Build()
	File_mapped_cloud_types_bacnet_proto = out.File
	file_mapped_cloud_types_bacnet_proto_rawDesc = nil
	file_mapped_cloud_types_bacnet_proto_goTypes = nil
	file_mapped_cloud_types_bacnet_proto_depIdxs = nil
}
