// Copyright 2020 Google LLC
// Copyright 2022 Mapped Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: mapped/cloud/types/metadata.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MetadataRecord) Reset() {
	*x = MetadataRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_types_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRecord) ProtoMessage() {}

func (x *MetadataRecord) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_types_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRecord.ProtoReflect.Descriptor instead.
func (*MetadataRecord) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_types_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MetadataValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*MetadataRecord `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *MetadataValue) Reset() {
	*x = MetadataValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_types_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataValue) ProtoMessage() {}

func (x *MetadataValue) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_types_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataValue.ProtoReflect.Descriptor instead.
func (*MetadataValue) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_types_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataValue) GetValues() []*MetadataRecord {
	if x != nil {
		return x.Values
	}
	return nil
}

type MetadataUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Update:
	//
	//	*MetadataUpdate_Granular_
	//	*MetadataUpdate_Replace
	Update isMetadataUpdate_Update `protobuf_oneof:"update"`
}

func (x *MetadataUpdate) Reset() {
	*x = MetadataUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_types_metadata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataUpdate) ProtoMessage() {}

func (x *MetadataUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_types_metadata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataUpdate.ProtoReflect.Descriptor instead.
func (*MetadataUpdate) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_types_metadata_proto_rawDescGZIP(), []int{2}
}

func (m *MetadataUpdate) GetUpdate() isMetadataUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *MetadataUpdate) GetGranular() *MetadataUpdate_Granular {
	if x, ok := x.GetUpdate().(*MetadataUpdate_Granular_); ok {
		return x.Granular
	}
	return nil
}

func (x *MetadataUpdate) GetReplace() *MetadataValue {
	if x, ok := x.GetUpdate().(*MetadataUpdate_Replace); ok {
		return x.Replace
	}
	return nil
}

type isMetadataUpdate_Update interface {
	isMetadataUpdate_Update()
}

type MetadataUpdate_Granular_ struct {
	Granular *MetadataUpdate_Granular `protobuf:"bytes,1,opt,name=granular,proto3,oneof"`
}

type MetadataUpdate_Replace struct {
	Replace *MetadataValue `protobuf:"bytes,2,opt,name=replace,proto3,oneof"`
}

func (*MetadataUpdate_Granular_) isMetadataUpdate_Update() {}

func (*MetadataUpdate_Replace) isMetadataUpdate_Update() {}

type MetadataRecordFilterExpression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *StringFilterExpression `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *StringFilterExpression `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MetadataRecordFilterExpression) Reset() {
	*x = MetadataRecordFilterExpression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_types_metadata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataRecordFilterExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRecordFilterExpression) ProtoMessage() {}

func (x *MetadataRecordFilterExpression) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_types_metadata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRecordFilterExpression.ProtoReflect.Descriptor instead.
func (*MetadataRecordFilterExpression) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_types_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataRecordFilterExpression) GetKey() *StringFilterExpression {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MetadataRecordFilterExpression) GetValue() *StringFilterExpression {
	if x != nil {
		return x.Value
	}
	return nil
}

type MetadataUpdate_Granular struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Add       []*MetadataRecord `protobuf:"bytes,1,rep,name=add,proto3" json:"add,omitempty"`
	Remove    []*MetadataRecord `protobuf:"bytes,2,rep,name=remove,proto3" json:"remove,omitempty"`
	RemoveAll []string          `protobuf:"bytes,3,rep,name=remove_all,json=removeAll,proto3" json:"remove_all,omitempty"`
}

func (x *MetadataUpdate_Granular) Reset() {
	*x = MetadataUpdate_Granular{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_types_metadata_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataUpdate_Granular) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataUpdate_Granular) ProtoMessage() {}

func (x *MetadataUpdate_Granular) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_types_metadata_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataUpdate_Granular.ProtoReflect.Descriptor instead.
func (*MetadataUpdate_Granular) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_types_metadata_proto_rawDescGZIP(), []int{2, 0}
}

func (x *MetadataUpdate_Granular) GetAdd() []*MetadataRecord {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *MetadataUpdate_Granular) GetRemove() []*MetadataRecord {
	if x != nil {
		return x.Remove
	}
	return nil
}

func (x *MetadataUpdate_Granular) GetRemoveAll() []string {
	if x != nil {
		return x.RemoveAll
	}
	return nil
}

var File_mapped_cloud_types_metadata_proto protoreflect.FileDescriptor

var file_mapped_cloud_types_metadata_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x1f, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2f,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x4b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x3a, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0xc2, 0x02, 0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x49, 0x0a, 0x08, 0x67, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61,
	0x72, 0x48, 0x00, 0x52, 0x08, 0x67, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x12, 0x3d, 0x0a,
	0x07, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x1a, 0x9b, 0x01, 0x0a,
	0x08, 0x47, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x12, 0x34, 0x0a, 0x03, 0x61, 0x64, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12,
	0x3a, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x42, 0x08, 0x0a, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x22, 0xaa, 0x01, 0x0a, 0x1e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x40, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x08, 0xe0, 0xd5, 0x24, 0x01, 0xf0, 0xd5, 0x24,
	0x01, 0x42, 0x56, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x22, 0x67,
	0x6f, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x70, 0x62, 0x2f,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x3b, 0x74, 0x79, 0x70, 0x65,
	0x73, 0xf8, 0x01, 0x01, 0xaa, 0x02, 0x12, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x43, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_mapped_cloud_types_metadata_proto_rawDescOnce sync.Once
	file_mapped_cloud_types_metadata_proto_rawDescData = file_mapped_cloud_types_metadata_proto_rawDesc
)

func file_mapped_cloud_types_metadata_proto_rawDescGZIP() []byte {
	file_mapped_cloud_types_metadata_proto_rawDescOnce.Do(func() {
		file_mapped_cloud_types_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapped_cloud_types_metadata_proto_rawDescData)
	})
	return file_mapped_cloud_types_metadata_proto_rawDescData
}

var file_mapped_cloud_types_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mapped_cloud_types_metadata_proto_goTypes = []interface{}{
	(*MetadataRecord)(nil),                 // 0: mapped.cloud.types.MetadataRecord
	(*MetadataValue)(nil),                  // 1: mapped.cloud.types.MetadataValue
	(*MetadataUpdate)(nil),                 // 2: mapped.cloud.types.MetadataUpdate
	(*MetadataRecordFilterExpression)(nil), // 3: mapped.cloud.types.MetadataRecordFilterExpression
	(*MetadataUpdate_Granular)(nil),        // 4: mapped.cloud.types.MetadataUpdate.Granular
	(*StringFilterExpression)(nil),         // 5: mapped.cloud.types.StringFilterExpression
}
var file_mapped_cloud_types_metadata_proto_depIdxs = []int32{
	0, // 0: mapped.cloud.types.MetadataValue.values:type_name -> mapped.cloud.types.MetadataRecord
	4, // 1: mapped.cloud.types.MetadataUpdate.granular:type_name -> mapped.cloud.types.MetadataUpdate.Granular
	1, // 2: mapped.cloud.types.MetadataUpdate.replace:type_name -> mapped.cloud.types.MetadataValue
	5, // 3: mapped.cloud.types.MetadataRecordFilterExpression.key:type_name -> mapped.cloud.types.StringFilterExpression
	5, // 4: mapped.cloud.types.MetadataRecordFilterExpression.value:type_name -> mapped.cloud.types.StringFilterExpression
	0, // 5: mapped.cloud.types.MetadataUpdate.Granular.add:type_name -> mapped.cloud.types.MetadataRecord
	0, // 6: mapped.cloud.types.MetadataUpdate.Granular.remove:type_name -> mapped.cloud.types.MetadataRecord
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_mapped_cloud_types_metadata_proto_init() }
func file_mapped_cloud_types_metadata_proto_init() {
	if File_mapped_cloud_types_metadata_proto != nil {
		return
	}
	file_mapped_cloud_types_filter_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mapped_cloud_types_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_types_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_types_metadata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_types_metadata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataRecordFilterExpression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_types_metadata_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataUpdate_Granular); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mapped_cloud_types_metadata_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*MetadataUpdate_Granular_)(nil),
		(*MetadataUpdate_Replace)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapped_cloud_types_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapped_cloud_types_metadata_proto_goTypes,
		DependencyIndexes: file_mapped_cloud_types_metadata_proto_depIdxs,
		MessageInfos:      file_mapped_cloud_types_metadata_proto_msgTypes,
	}.Build()
	File_mapped_cloud_types_metadata_proto = out.File
	file_mapped_cloud_types_metadata_proto_rawDesc = nil
	file_mapped_cloud_types_metadata_proto_goTypes = nil
	file_mapped_cloud_types_metadata_proto_depIdxs = nil
}
