// Copyright 2020 Google LLC
// Copyright 2022 Mapped Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: mapped/cloud/types/metadata.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string                     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value      string                     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TypedValue *MetadataRecord_TypedValue `protobuf:"bytes,3,opt,name=typed_value,json=typedValue,proto3" json:"typed_value,omitempty"`
}

func (x *MetadataRecord) Reset() {
	*x = MetadataRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_types_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRecord) ProtoMessage() {}

func (x *MetadataRecord) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_types_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRecord.ProtoReflect.Descriptor instead.
func (*MetadataRecord) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_types_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MetadataRecord) GetTypedValue() *MetadataRecord_TypedValue {
	if x != nil {
		return x.TypedValue
	}
	return nil
}

type MetadataValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*MetadataRecord `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *MetadataValue) Reset() {
	*x = MetadataValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_types_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataValue) ProtoMessage() {}

func (x *MetadataValue) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_types_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataValue.ProtoReflect.Descriptor instead.
func (*MetadataValue) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_types_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataValue) GetValues() []*MetadataRecord {
	if x != nil {
		return x.Values
	}
	return nil
}

type MetadataUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Update:
	//
	//	*MetadataUpdate_Granular_
	//	*MetadataUpdate_Replace
	Update isMetadataUpdate_Update `protobuf_oneof:"update"`
}

func (x *MetadataUpdate) Reset() {
	*x = MetadataUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_types_metadata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataUpdate) ProtoMessage() {}

func (x *MetadataUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_types_metadata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataUpdate.ProtoReflect.Descriptor instead.
func (*MetadataUpdate) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_types_metadata_proto_rawDescGZIP(), []int{2}
}

func (m *MetadataUpdate) GetUpdate() isMetadataUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *MetadataUpdate) GetGranular() *MetadataUpdate_Granular {
	if x, ok := x.GetUpdate().(*MetadataUpdate_Granular_); ok {
		return x.Granular
	}
	return nil
}

func (x *MetadataUpdate) GetReplace() *MetadataValue {
	if x, ok := x.GetUpdate().(*MetadataUpdate_Replace); ok {
		return x.Replace
	}
	return nil
}

type isMetadataUpdate_Update interface {
	isMetadataUpdate_Update()
}

type MetadataUpdate_Granular_ struct {
	Granular *MetadataUpdate_Granular `protobuf:"bytes,1,opt,name=granular,proto3,oneof"`
}

type MetadataUpdate_Replace struct {
	Replace *MetadataValue `protobuf:"bytes,2,opt,name=replace,proto3,oneof"`
}

func (*MetadataUpdate_Granular_) isMetadataUpdate_Update() {}

func (*MetadataUpdate_Replace) isMetadataUpdate_Update() {}

type MetadataRecordFilterExpression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *StringFilterExpression `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *StringFilterExpression `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MetadataRecordFilterExpression) Reset() {
	*x = MetadataRecordFilterExpression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_types_metadata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataRecordFilterExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRecordFilterExpression) ProtoMessage() {}

func (x *MetadataRecordFilterExpression) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_types_metadata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRecordFilterExpression.ProtoReflect.Descriptor instead.
func (*MetadataRecordFilterExpression) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_types_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataRecordFilterExpression) GetKey() *StringFilterExpression {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MetadataRecordFilterExpression) GetValue() *StringFilterExpression {
	if x != nil {
		return x.Value
	}
	return nil
}

type MetadataRecord_TypedValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*MetadataRecord_TypedValue_StringValue
	//	*MetadataRecord_TypedValue_BoolValue
	//	*MetadataRecord_TypedValue_TimestampValue
	//	*MetadataRecord_TypedValue_JsonValue
	//	*MetadataRecord_TypedValue_Int32Value
	//	*MetadataRecord_TypedValue_IntValue
	//	*MetadataRecord_TypedValue_Uint32Value
	//	*MetadataRecord_TypedValue_Uint64Value
	//	*MetadataRecord_TypedValue_DoubleValue
	Value isMetadataRecord_TypedValue_Value `protobuf_oneof:"value"`
}

func (x *MetadataRecord_TypedValue) Reset() {
	*x = MetadataRecord_TypedValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_types_metadata_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataRecord_TypedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRecord_TypedValue) ProtoMessage() {}

func (x *MetadataRecord_TypedValue) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_types_metadata_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRecord_TypedValue.ProtoReflect.Descriptor instead.
func (*MetadataRecord_TypedValue) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_types_metadata_proto_rawDescGZIP(), []int{0, 0}
}

func (m *MetadataRecord_TypedValue) GetValue() isMetadataRecord_TypedValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *MetadataRecord_TypedValue) GetStringValue() string {
	if x, ok := x.GetValue().(*MetadataRecord_TypedValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *MetadataRecord_TypedValue) GetBoolValue() bool {
	if x, ok := x.GetValue().(*MetadataRecord_TypedValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *MetadataRecord_TypedValue) GetTimestampValue() *timestamppb.Timestamp {
	if x, ok := x.GetValue().(*MetadataRecord_TypedValue_TimestampValue); ok {
		return x.TimestampValue
	}
	return nil
}

func (x *MetadataRecord_TypedValue) GetJsonValue() string {
	if x, ok := x.GetValue().(*MetadataRecord_TypedValue_JsonValue); ok {
		return x.JsonValue
	}
	return ""
}

func (x *MetadataRecord_TypedValue) GetInt32Value() int32 {
	if x, ok := x.GetValue().(*MetadataRecord_TypedValue_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (x *MetadataRecord_TypedValue) GetIntValue() int64 {
	if x, ok := x.GetValue().(*MetadataRecord_TypedValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (x *MetadataRecord_TypedValue) GetUint32Value() uint32 {
	if x, ok := x.GetValue().(*MetadataRecord_TypedValue_Uint32Value); ok {
		return x.Uint32Value
	}
	return 0
}

func (x *MetadataRecord_TypedValue) GetUint64Value() uint64 {
	if x, ok := x.GetValue().(*MetadataRecord_TypedValue_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (x *MetadataRecord_TypedValue) GetDoubleValue() float64 {
	if x, ok := x.GetValue().(*MetadataRecord_TypedValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

type isMetadataRecord_TypedValue_Value interface {
	isMetadataRecord_TypedValue_Value()
}

type MetadataRecord_TypedValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type MetadataRecord_TypedValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type MetadataRecord_TypedValue_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type MetadataRecord_TypedValue_JsonValue struct {
	JsonValue string `protobuf:"bytes,4,opt,name=json_value,json=jsonValue,proto3,oneof"`
}

type MetadataRecord_TypedValue_Int32Value struct {
	Int32Value int32 `protobuf:"varint,5,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type MetadataRecord_TypedValue_IntValue struct {
	IntValue int64 `protobuf:"varint,6,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MetadataRecord_TypedValue_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,7,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type MetadataRecord_TypedValue_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,8,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type MetadataRecord_TypedValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,9,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

func (*MetadataRecord_TypedValue_StringValue) isMetadataRecord_TypedValue_Value() {}

func (*MetadataRecord_TypedValue_BoolValue) isMetadataRecord_TypedValue_Value() {}

func (*MetadataRecord_TypedValue_TimestampValue) isMetadataRecord_TypedValue_Value() {}

func (*MetadataRecord_TypedValue_JsonValue) isMetadataRecord_TypedValue_Value() {}

func (*MetadataRecord_TypedValue_Int32Value) isMetadataRecord_TypedValue_Value() {}

func (*MetadataRecord_TypedValue_IntValue) isMetadataRecord_TypedValue_Value() {}

func (*MetadataRecord_TypedValue_Uint32Value) isMetadataRecord_TypedValue_Value() {}

func (*MetadataRecord_TypedValue_Uint64Value) isMetadataRecord_TypedValue_Value() {}

func (*MetadataRecord_TypedValue_DoubleValue) isMetadataRecord_TypedValue_Value() {}

type MetadataUpdate_Granular struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Add       []*MetadataRecord `protobuf:"bytes,1,rep,name=add,proto3" json:"add,omitempty"`
	Remove    []*MetadataRecord `protobuf:"bytes,2,rep,name=remove,proto3" json:"remove,omitempty"`
	RemoveAll []string          `protobuf:"bytes,3,rep,name=remove_all,json=removeAll,proto3" json:"remove_all,omitempty"`
}

func (x *MetadataUpdate_Granular) Reset() {
	*x = MetadataUpdate_Granular{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_types_metadata_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataUpdate_Granular) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataUpdate_Granular) ProtoMessage() {}

func (x *MetadataUpdate_Granular) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_types_metadata_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataUpdate_Granular.ProtoReflect.Descriptor instead.
func (*MetadataUpdate_Granular) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_types_metadata_proto_rawDescGZIP(), []int{2, 0}
}

func (x *MetadataUpdate_Granular) GetAdd() []*MetadataRecord {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *MetadataUpdate_Granular) GetRemove() []*MetadataRecord {
	if x != nil {
		return x.Remove
	}
	return nil
}

func (x *MetadataUpdate_Granular) GetRemoveAll() []string {
	if x != nil {
		return x.RemoveAll
	}
	return nil
}

var File_mapped_cloud_types_metadata_proto protoreflect.FileDescriptor

var file_mapped_cloud_types_metadata_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x1f, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2f,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xff, 0x03, 0x0a, 0x0e, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x64, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6d, 0x61, 0x70, 0x70,
	0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x64, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x1a, 0xf4, 0x02, 0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x64, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09,
	0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x45, 0x0a, 0x0f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00,
	0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1f, 0x0a, 0x0a, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x69, 0x6e,
	0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x75, 0x69, 0x6e, 0x74,
	0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00,
	0x52, 0x0b, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a,
	0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4b, 0x0a, 0x0d, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3a, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d,
	0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xc2, 0x02, 0x0a, 0x0e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x49, 0x0a, 0x08, 0x67,
	0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x48, 0x00, 0x52, 0x08, 0x67, 0x72,
	0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x12, 0x3d, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x1a, 0x9b, 0x01, 0x0a, 0x08, 0x47, 0x72, 0x61, 0x6e, 0x75, 0x6c,
	0x61, 0x72, 0x12, 0x34, 0x0a, 0x03, 0x61, 0x64, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12, 0x3a, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65,
	0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x61,
	0x6c, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x41, 0x6c, 0x6c, 0x42, 0x08, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0xaa, 0x01,
	0x0a, 0x1e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x3c, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e,
	0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x40,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e,
	0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x08, 0xe0, 0xd5, 0x24, 0x01, 0xf0, 0xd5, 0x24, 0x01, 0x42, 0x56, 0x0a, 0x16, 0x63, 0x6f,
	0x6d, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x22, 0x67, 0x6f, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65,
	0x64, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x73, 0xf8, 0x01, 0x01, 0xaa, 0x02, 0x12,
	0x4d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mapped_cloud_types_metadata_proto_rawDescOnce sync.Once
	file_mapped_cloud_types_metadata_proto_rawDescData = file_mapped_cloud_types_metadata_proto_rawDesc
)

func file_mapped_cloud_types_metadata_proto_rawDescGZIP() []byte {
	file_mapped_cloud_types_metadata_proto_rawDescOnce.Do(func() {
		file_mapped_cloud_types_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapped_cloud_types_metadata_proto_rawDescData)
	})
	return file_mapped_cloud_types_metadata_proto_rawDescData
}

var file_mapped_cloud_types_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mapped_cloud_types_metadata_proto_goTypes = []interface{}{
	(*MetadataRecord)(nil),                 // 0: mapped.cloud.types.MetadataRecord
	(*MetadataValue)(nil),                  // 1: mapped.cloud.types.MetadataValue
	(*MetadataUpdate)(nil),                 // 2: mapped.cloud.types.MetadataUpdate
	(*MetadataRecordFilterExpression)(nil), // 3: mapped.cloud.types.MetadataRecordFilterExpression
	(*MetadataRecord_TypedValue)(nil),      // 4: mapped.cloud.types.MetadataRecord.TypedValue
	(*MetadataUpdate_Granular)(nil),        // 5: mapped.cloud.types.MetadataUpdate.Granular
	(*StringFilterExpression)(nil),         // 6: mapped.cloud.types.StringFilterExpression
	(*timestamppb.Timestamp)(nil),          // 7: google.protobuf.Timestamp
}
var file_mapped_cloud_types_metadata_proto_depIdxs = []int32{
	4, // 0: mapped.cloud.types.MetadataRecord.typed_value:type_name -> mapped.cloud.types.MetadataRecord.TypedValue
	0, // 1: mapped.cloud.types.MetadataValue.values:type_name -> mapped.cloud.types.MetadataRecord
	5, // 2: mapped.cloud.types.MetadataUpdate.granular:type_name -> mapped.cloud.types.MetadataUpdate.Granular
	1, // 3: mapped.cloud.types.MetadataUpdate.replace:type_name -> mapped.cloud.types.MetadataValue
	6, // 4: mapped.cloud.types.MetadataRecordFilterExpression.key:type_name -> mapped.cloud.types.StringFilterExpression
	6, // 5: mapped.cloud.types.MetadataRecordFilterExpression.value:type_name -> mapped.cloud.types.StringFilterExpression
	7, // 6: mapped.cloud.types.MetadataRecord.TypedValue.timestamp_value:type_name -> google.protobuf.Timestamp
	0, // 7: mapped.cloud.types.MetadataUpdate.Granular.add:type_name -> mapped.cloud.types.MetadataRecord
	0, // 8: mapped.cloud.types.MetadataUpdate.Granular.remove:type_name -> mapped.cloud.types.MetadataRecord
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_mapped_cloud_types_metadata_proto_init() }
func file_mapped_cloud_types_metadata_proto_init() {
	if File_mapped_cloud_types_metadata_proto != nil {
		return
	}
	file_mapped_cloud_types_filter_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mapped_cloud_types_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_types_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_types_metadata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_types_metadata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataRecordFilterExpression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_types_metadata_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataRecord_TypedValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapped_cloud_types_metadata_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataUpdate_Granular); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mapped_cloud_types_metadata_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*MetadataUpdate_Granular_)(nil),
		(*MetadataUpdate_Replace)(nil),
	}
	file_mapped_cloud_types_metadata_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*MetadataRecord_TypedValue_StringValue)(nil),
		(*MetadataRecord_TypedValue_BoolValue)(nil),
		(*MetadataRecord_TypedValue_TimestampValue)(nil),
		(*MetadataRecord_TypedValue_JsonValue)(nil),
		(*MetadataRecord_TypedValue_Int32Value)(nil),
		(*MetadataRecord_TypedValue_IntValue)(nil),
		(*MetadataRecord_TypedValue_Uint32Value)(nil),
		(*MetadataRecord_TypedValue_Uint64Value)(nil),
		(*MetadataRecord_TypedValue_DoubleValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapped_cloud_types_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapped_cloud_types_metadata_proto_goTypes,
		DependencyIndexes: file_mapped_cloud_types_metadata_proto_depIdxs,
		MessageInfos:      file_mapped_cloud_types_metadata_proto_msgTypes,
	}.Build()
	File_mapped_cloud_types_metadata_proto = out.File
	file_mapped_cloud_types_metadata_proto_rawDesc = nil
	file_mapped_cloud_types_metadata_proto_goTypes = nil
	file_mapped_cloud_types_metadata_proto_depIdxs = nil
}
