// Copyright 2020 Google LLC
// Copyright 2022 Mapped Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: mapped/cloud/types/period.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeriodIncrement int32

const (
	// No increment.
	PeriodIncrement_PERIOD_INCREMENT_UNSPECIFIED PeriodIncrement = 0
	// Increment by 1 second.
	PeriodIncrement_PERIOD_INCREMENT_SECOND PeriodIncrement = 1
	// Increment by 1 minute.
	PeriodIncrement_PERIOD_INCREMENT_MINUTE PeriodIncrement = 2
	// Increment by 1 hour.
	PeriodIncrement_PERIOD_INCREMENT_HOUR PeriodIncrement = 3
	// Increment by 1 day.
	PeriodIncrement_PERIOD_INCREMENT_DAY PeriodIncrement = 4
	// Increment by 1 week.
	PeriodIncrement_PERIOD_INCREMENT_WEEK PeriodIncrement = 5
	// Increment by 1 month.
	PeriodIncrement_PERIOD_INCREMENT_MONTH PeriodIncrement = 6
	// Increment by 1 year.
	PeriodIncrement_PERIOD_INCREMENT_YEAR PeriodIncrement = 7
)

// Enum value maps for PeriodIncrement.
var (
	PeriodIncrement_name = map[int32]string{
		0: "PERIOD_INCREMENT_UNSPECIFIED",
		1: "PERIOD_INCREMENT_SECOND",
		2: "PERIOD_INCREMENT_MINUTE",
		3: "PERIOD_INCREMENT_HOUR",
		4: "PERIOD_INCREMENT_DAY",
		5: "PERIOD_INCREMENT_WEEK",
		6: "PERIOD_INCREMENT_MONTH",
		7: "PERIOD_INCREMENT_YEAR",
	}
	PeriodIncrement_value = map[string]int32{
		"PERIOD_INCREMENT_UNSPECIFIED": 0,
		"PERIOD_INCREMENT_SECOND":      1,
		"PERIOD_INCREMENT_MINUTE":      2,
		"PERIOD_INCREMENT_HOUR":        3,
		"PERIOD_INCREMENT_DAY":         4,
		"PERIOD_INCREMENT_WEEK":        5,
		"PERIOD_INCREMENT_MONTH":       6,
		"PERIOD_INCREMENT_YEAR":        7,
	}
)

func (x PeriodIncrement) Enum() *PeriodIncrement {
	p := new(PeriodIncrement)
	*p = x
	return p
}

func (x PeriodIncrement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeriodIncrement) Descriptor() protoreflect.EnumDescriptor {
	return file_mapped_cloud_types_period_proto_enumTypes[0].Descriptor()
}

func (PeriodIncrement) Type() protoreflect.EnumType {
	return &file_mapped_cloud_types_period_proto_enumTypes[0]
}

func (x PeriodIncrement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeriodIncrement.Descriptor instead.
func (PeriodIncrement) EnumDescriptor() ([]byte, []int) {
	return file_mapped_cloud_types_period_proto_rawDescGZIP(), []int{0}
}

// Represents a period of time.
type Period struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count     int32           `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Increment PeriodIncrement `protobuf:"varint,2,opt,name=increment,proto3,enum=mapped.cloud.types.PeriodIncrement" json:"increment,omitempty"`
}

func (x *Period) Reset() {
	*x = Period{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapped_cloud_types_period_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_mapped_cloud_types_period_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_mapped_cloud_types_period_proto_rawDescGZIP(), []int{0}
}

func (x *Period) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Period) GetIncrement() PeriodIncrement {
	if x != nil {
		return x.Increment
	}
	return PeriodIncrement_PERIOD_INCREMENT_UNSPECIFIED
}

var File_mapped_cloud_types_period_proto protoreflect.FileDescriptor

var file_mapped_cloud_types_period_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x61, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65,
	0x64, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x69,
	0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2a, 0xf4, 0x01, 0x0a, 0x0f, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x1c,
	0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x49, 0x4e, 0x43, 0x52, 0x45, 0x4d, 0x45, 0x4e, 0x54,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b,
	0x0a, 0x17, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x49, 0x4e, 0x43, 0x52, 0x45, 0x4d, 0x45,
	0x4e, 0x54, 0x5f, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x50,
	0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x49, 0x4e, 0x43, 0x52, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f,
	0x4d, 0x49, 0x4e, 0x55, 0x54, 0x45, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x45, 0x52, 0x49,
	0x4f, 0x44, 0x5f, 0x49, 0x4e, 0x43, 0x52, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x48, 0x4f, 0x55,
	0x52, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x49, 0x4e,
	0x43, 0x52, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x44, 0x41, 0x59, 0x10, 0x04, 0x12, 0x19, 0x0a,
	0x15, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x49, 0x4e, 0x43, 0x52, 0x45, 0x4d, 0x45, 0x4e,
	0x54, 0x5f, 0x57, 0x45, 0x45, 0x4b, 0x10, 0x05, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x45, 0x52, 0x49,
	0x4f, 0x44, 0x5f, 0x49, 0x4e, 0x43, 0x52, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x4f, 0x4e,
	0x54, 0x48, 0x10, 0x06, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x49,
	0x4e, 0x43, 0x52, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x59, 0x45, 0x41, 0x52, 0x10, 0x07, 0x42,
	0x56, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x22, 0x67, 0x6f, 0x2e,
	0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x73, 0xf8,
	0x01, 0x01, 0xaa, 0x02, 0x12, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x2e, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mapped_cloud_types_period_proto_rawDescOnce sync.Once
	file_mapped_cloud_types_period_proto_rawDescData = file_mapped_cloud_types_period_proto_rawDesc
)

func file_mapped_cloud_types_period_proto_rawDescGZIP() []byte {
	file_mapped_cloud_types_period_proto_rawDescOnce.Do(func() {
		file_mapped_cloud_types_period_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapped_cloud_types_period_proto_rawDescData)
	})
	return file_mapped_cloud_types_period_proto_rawDescData
}

var file_mapped_cloud_types_period_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mapped_cloud_types_period_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mapped_cloud_types_period_proto_goTypes = []interface{}{
	(PeriodIncrement)(0), // 0: mapped.cloud.types.PeriodIncrement
	(*Period)(nil),       // 1: mapped.cloud.types.Period
}
var file_mapped_cloud_types_period_proto_depIdxs = []int32{
	0, // 0: mapped.cloud.types.Period.increment:type_name -> mapped.cloud.types.PeriodIncrement
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mapped_cloud_types_period_proto_init() }
func file_mapped_cloud_types_period_proto_init() {
	if File_mapped_cloud_types_period_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mapped_cloud_types_period_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Period); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapped_cloud_types_period_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapped_cloud_types_period_proto_goTypes,
		DependencyIndexes: file_mapped_cloud_types_period_proto_depIdxs,
		EnumInfos:         file_mapped_cloud_types_period_proto_enumTypes,
		MessageInfos:      file_mapped_cloud_types_period_proto_msgTypes,
	}.Build()
	File_mapped_cloud_types_period_proto = out.File
	file_mapped_cloud_types_period_proto_rawDesc = nil
	file_mapped_cloud_types_period_proto_goTypes = nil
	file_mapped_cloud_types_period_proto_depIdxs = nil
}
