// ******************************************************************************************************
// Copyright 2022 Mapped Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ******************************************************************************************************

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: mapped/cloud/api/niagara/niagara.proto

package niagara

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NiagaraService_ListChildComponents_FullMethodName      = "/mapped.cloud.api.niagara.NiagaraService/ListChildComponents"
	NiagaraService_FindComponents_FullMethodName           = "/mapped.cloud.api.niagara.NiagaraService/FindComponents"
	NiagaraService_GetComponentSummary_FullMethodName      = "/mapped.cloud.api.niagara.NiagaraService/GetComponentSummary"
	NiagaraService_GetComponentDetails_FullMethodName      = "/mapped.cloud.api.niagara.NiagaraService/GetComponentDetails"
	NiagaraService_GetComponentAncestors_FullMethodName    = "/mapped.cloud.api.niagara.NiagaraService/GetComponentAncestors"
	NiagaraService_UpsertDeviceSubscription_FullMethodName = "/mapped.cloud.api.niagara.NiagaraService/UpsertDeviceSubscription"
	NiagaraService_Reset_FullMethodName                    = "/mapped.cloud.api.niagara.NiagaraService/Reset"
	NiagaraService_Ping_FullMethodName                     = "/mapped.cloud.api.niagara.NiagaraService/Ping"
)

// NiagaraServiceClient is the client API for NiagaraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NiagaraServiceClient interface {
	ListChildComponents(ctx context.Context, in *ListChildComponentsRequest, opts ...grpc.CallOption) (*ListChildComponentsResponse, error)
	FindComponents(ctx context.Context, in *FindComponentsRequest, opts ...grpc.CallOption) (*FindComponentsResponse, error)
	GetComponentSummary(ctx context.Context, in *GetComponentSummaryRequest, opts ...grpc.CallOption) (*GetComponentSummaryResponse, error)
	GetComponentDetails(ctx context.Context, in *GetComponentDetailsRequest, opts ...grpc.CallOption) (*GetComponentDetailsResponse, error)
	GetComponentAncestors(ctx context.Context, in *GetComponentAncestorsRequest, opts ...grpc.CallOption) (*GetComponentAncestorsResponse, error)
	UpsertDeviceSubscription(ctx context.Context, in *UpsertDeviceSubscriptionRequest, opts ...grpc.CallOption) (*UpsertDeviceSubscriptionResponse, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type niagaraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNiagaraServiceClient(cc grpc.ClientConnInterface) NiagaraServiceClient {
	return &niagaraServiceClient{cc}
}

func (c *niagaraServiceClient) ListChildComponents(ctx context.Context, in *ListChildComponentsRequest, opts ...grpc.CallOption) (*ListChildComponentsResponse, error) {
	out := new(ListChildComponentsResponse)
	err := c.cc.Invoke(ctx, NiagaraService_ListChildComponents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *niagaraServiceClient) FindComponents(ctx context.Context, in *FindComponentsRequest, opts ...grpc.CallOption) (*FindComponentsResponse, error) {
	out := new(FindComponentsResponse)
	err := c.cc.Invoke(ctx, NiagaraService_FindComponents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *niagaraServiceClient) GetComponentSummary(ctx context.Context, in *GetComponentSummaryRequest, opts ...grpc.CallOption) (*GetComponentSummaryResponse, error) {
	out := new(GetComponentSummaryResponse)
	err := c.cc.Invoke(ctx, NiagaraService_GetComponentSummary_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *niagaraServiceClient) GetComponentDetails(ctx context.Context, in *GetComponentDetailsRequest, opts ...grpc.CallOption) (*GetComponentDetailsResponse, error) {
	out := new(GetComponentDetailsResponse)
	err := c.cc.Invoke(ctx, NiagaraService_GetComponentDetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *niagaraServiceClient) GetComponentAncestors(ctx context.Context, in *GetComponentAncestorsRequest, opts ...grpc.CallOption) (*GetComponentAncestorsResponse, error) {
	out := new(GetComponentAncestorsResponse)
	err := c.cc.Invoke(ctx, NiagaraService_GetComponentAncestors_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *niagaraServiceClient) UpsertDeviceSubscription(ctx context.Context, in *UpsertDeviceSubscriptionRequest, opts ...grpc.CallOption) (*UpsertDeviceSubscriptionResponse, error) {
	out := new(UpsertDeviceSubscriptionResponse)
	err := c.cc.Invoke(ctx, NiagaraService_UpsertDeviceSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *niagaraServiceClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, NiagaraService_Reset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *niagaraServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, NiagaraService_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NiagaraServiceServer is the server API for NiagaraService service.
// All implementations must embed UnimplementedNiagaraServiceServer
// for forward compatibility
type NiagaraServiceServer interface {
	ListChildComponents(context.Context, *ListChildComponentsRequest) (*ListChildComponentsResponse, error)
	FindComponents(context.Context, *FindComponentsRequest) (*FindComponentsResponse, error)
	GetComponentSummary(context.Context, *GetComponentSummaryRequest) (*GetComponentSummaryResponse, error)
	GetComponentDetails(context.Context, *GetComponentDetailsRequest) (*GetComponentDetailsResponse, error)
	GetComponentAncestors(context.Context, *GetComponentAncestorsRequest) (*GetComponentAncestorsResponse, error)
	UpsertDeviceSubscription(context.Context, *UpsertDeviceSubscriptionRequest) (*UpsertDeviceSubscriptionResponse, error)
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedNiagaraServiceServer()
}

// UnimplementedNiagaraServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNiagaraServiceServer struct {
}

func (UnimplementedNiagaraServiceServer) ListChildComponents(context.Context, *ListChildComponentsRequest) (*ListChildComponentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChildComponents not implemented")
}
func (UnimplementedNiagaraServiceServer) FindComponents(context.Context, *FindComponentsRequest) (*FindComponentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindComponents not implemented")
}
func (UnimplementedNiagaraServiceServer) GetComponentSummary(context.Context, *GetComponentSummaryRequest) (*GetComponentSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponentSummary not implemented")
}
func (UnimplementedNiagaraServiceServer) GetComponentDetails(context.Context, *GetComponentDetailsRequest) (*GetComponentDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponentDetails not implemented")
}
func (UnimplementedNiagaraServiceServer) GetComponentAncestors(context.Context, *GetComponentAncestorsRequest) (*GetComponentAncestorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponentAncestors not implemented")
}
func (UnimplementedNiagaraServiceServer) UpsertDeviceSubscription(context.Context, *UpsertDeviceSubscriptionRequest) (*UpsertDeviceSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertDeviceSubscription not implemented")
}
func (UnimplementedNiagaraServiceServer) Reset(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedNiagaraServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNiagaraServiceServer) mustEmbedUnimplementedNiagaraServiceServer() {}

// UnsafeNiagaraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NiagaraServiceServer will
// result in compilation errors.
type UnsafeNiagaraServiceServer interface {
	mustEmbedUnimplementedNiagaraServiceServer()
}

func RegisterNiagaraServiceServer(s grpc.ServiceRegistrar, srv NiagaraServiceServer) {
	s.RegisterService(&NiagaraService_ServiceDesc, srv)
}

func _NiagaraService_ListChildComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChildComponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NiagaraServiceServer).ListChildComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NiagaraService_ListChildComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NiagaraServiceServer).ListChildComponents(ctx, req.(*ListChildComponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NiagaraService_FindComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindComponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NiagaraServiceServer).FindComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NiagaraService_FindComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NiagaraServiceServer).FindComponents(ctx, req.(*FindComponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NiagaraService_GetComponentSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComponentSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NiagaraServiceServer).GetComponentSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NiagaraService_GetComponentSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NiagaraServiceServer).GetComponentSummary(ctx, req.(*GetComponentSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NiagaraService_GetComponentDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComponentDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NiagaraServiceServer).GetComponentDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NiagaraService_GetComponentDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NiagaraServiceServer).GetComponentDetails(ctx, req.(*GetComponentDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NiagaraService_GetComponentAncestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComponentAncestorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NiagaraServiceServer).GetComponentAncestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NiagaraService_GetComponentAncestors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NiagaraServiceServer).GetComponentAncestors(ctx, req.(*GetComponentAncestorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NiagaraService_UpsertDeviceSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertDeviceSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NiagaraServiceServer).UpsertDeviceSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NiagaraService_UpsertDeviceSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NiagaraServiceServer).UpsertDeviceSubscription(ctx, req.(*UpsertDeviceSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NiagaraService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NiagaraServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NiagaraService_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NiagaraServiceServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NiagaraService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NiagaraServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NiagaraService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NiagaraServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NiagaraService_ServiceDesc is the grpc.ServiceDesc for NiagaraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NiagaraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mapped.cloud.api.niagara.NiagaraService",
	HandlerType: (*NiagaraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListChildComponents",
			Handler:    _NiagaraService_ListChildComponents_Handler,
		},
		{
			MethodName: "FindComponents",
			Handler:    _NiagaraService_FindComponents_Handler,
		},
		{
			MethodName: "GetComponentSummary",
			Handler:    _NiagaraService_GetComponentSummary_Handler,
		},
		{
			MethodName: "GetComponentDetails",
			Handler:    _NiagaraService_GetComponentDetails_Handler,
		},
		{
			MethodName: "GetComponentAncestors",
			Handler:    _NiagaraService_GetComponentAncestors_Handler,
		},
		{
			MethodName: "UpsertDeviceSubscription",
			Handler:    _NiagaraService_UpsertDeviceSubscription_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _NiagaraService_Reset_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _NiagaraService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mapped/cloud/api/niagara/niagara.proto",
}
